name: DailyDiary
options:
  bundleIdPrefix: com.dailydiary
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  defaultConfig: Debug

settings:
  SWIFT_VERSION: "5.9"
  GENERATE_INFOPLIST_FILE: false

targets:
  DailyDiary:
    type: application
    platform: iOS
    sources:
      - DailyDiary
    settings:
      INFOPLIST_FILE: DailyDiary/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.dailydiary.app
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      TARGETED_DEVICE_FAMILY: "1"
      SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
      SUPPORTS_MACCATALYST: false
    resources:
      - DailyDiary/Resources/Assets.xcassets
